name = "drkushalkharel"
type = "javascript"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
main = "out/server.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "modules"
dir = ".next"
main = ".next/standalone/server.js"

[env.production]
vars = { ENVIRONMENT = "production" }
