import Link from "next/link";
import type { Pillar } from "../data/pillars";

const siteUrl = "https://drkushalkharel.com.np";
const internalLinks = [
  ["Online psychiatrist in Nepal", "/online-psychiatrist-nepal"], ["Dr. Kushal Kharel", "/best-psychiatrist-nepal"],
  ["depression guide", "/depression"], ["anxiety guide", "/anxiety"], ["OCD guide", "/ocd"], ["ADHD guide", "/adhd"],
  ["bipolar disorder guide", "/bipolar-disorder"], ["schizophrenia guide", "/schizophrenia"], ["mental-health screening", "/mental-health-screening"], ["contact the clinic", "/contact"], ["mental-health blog", "/blog"],
];
const faqs = [
  ["Can this condition be treated?", "Many people improve substantially with an accurate diagnosis, a plan that fits their circumstances and consistent follow-up. The aim is symptom relief, recovery of daily functioning and prevention of future episodes."],
  ["Do I need to see a psychiatrist?", "A psychiatric assessment is sensible when symptoms persist, affect daily life, cause distress, recur, or involve safety concerns. You do not need to wait until a problem becomes severe."],
  ["Will I definitely need medication?", "No. Treatment is individualised after psychiatric assessment. Medication may be helpful for some people, while therapy, lifestyle support, family work or a combination may be the right starting point for others."],
  ["Is online consultation available?", "Online consultation can suit selected initial assessments, follow-ups, medication reviews and psychoeducation. It is not suitable for an immediate safety risk or a medical emergency."],
  ["How long does treatment take?", "It varies with diagnosis, severity, previous episodes, life circumstances and response. Follow-up allows the plan to be adjusted rather than judged after one visit."],
  ["Can stress cause these symptoms?", "Stress can trigger or worsen symptoms, but it is not the whole explanation for everyone. Assessment looks at psychological, social, physical and biological factors."],
  ["Are these symptoms a sign of weakness?", "No. Mental-health conditions are health conditions. Asking for assessment is a practical step, not a personal failure."],
  ["Can family attend?", "With the patient’s agreement, family input can be very helpful, especially for history, education, safety planning and practical support."],
  ["What should I bring to the first visit?", "Bring a list of medicines, previous reports if available, and notes about symptoms, sleep and questions. A trusted person can attend if you wish."],
  ["Can I stop medicine when I feel better?", "Do not stop or change prescribed psychiatric medicine suddenly. Discuss timing and a gradual, safe plan with the prescriber."],
  ["Are therapy sessions confidential?", "Confidentiality is a core part of psychiatric care, with limited safety and legal exceptions that should be explained clearly during consultation."],
  ["Can alcohol or drugs make things worse?", "Yes. They can worsen sleep, mood, anxiety, psychosis, impulsivity and medication side effects. Honest discussion helps create a safer plan."],
  ["What if the first treatment does not help enough?", "That is useful information, not failure. The diagnosis, therapy approach, practical barriers and medication plan can all be reviewed."],
  ["Can I work or study while receiving treatment?", "Often yes, and recovery plans should support meaningful roles. Temporary adjustments may be needed when symptoms are severe."],
  ["How can I support someone I love?", "Listen, avoid blame, take safety concerns seriously, encourage professional help and ask what practical support would be useful."],
];

export default function PillarArticle({ pillar }: { pillar: Pillar }) {
  const url = `${siteUrl}/${pillar.slug}`;
  const sections = [["Symptoms", pillar.symptoms], ["Causes", pillar.causes], ["Risk factors", pillar.risks], ["Diagnosis", pillar.diagnosis], ["Differential diagnosis", pillar.differential], ["Investigations", pillar.investigations], ["Evidence-based treatment", pillar.treatment], ["Medication overview", pillar.medication], ["Therapy: CBT, DBT and beyond", pillar.therapy], ["Family interventions", pillar.family], ["Lifestyle support", pillar.lifestyle], ["Relapse prevention", pillar.relapse], ["Your patient journey", pillar.journey]];
  const graph = [
    { "@type": "MedicalWebPage", name: pillar.title, url, description: pillar.meta, about: { "@type": "MedicalCondition", name: pillar.condition }, medicalAudience: ["Patient", "Caregiver"] },
    { "@type": "Physician", name: "Dr. Kushal Kharel", honorificSuffix: "MD Psychiatry", medicalSpecialty: "Psychiatry", address: { "@type": "PostalAddress", addressLocality: "Kathmandu", addressCountry: "NP" } },
    { "@type": "Article", headline: pillar.title, description: pillar.meta, author: { "@type": "Person", name: "Dr. Kushal Kharel" }, reviewer: { "@type": "Person", name: "Dr. Kushal Kharel" }, mainEntityOfPage: url },
    { "@type": "FAQPage", mainEntity: faqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: pillar.title, item: url }] }
  ];
  return <main className="min-h-screen bg-stone-50 text-stone-900"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@graph": graph }) }} />
    <header className="bg-white"><div className="mx-auto max-w-5xl px-6 pb-12 pt-28 lg:px-8"><p className="text-sm font-semibold uppercase tracking-[3px] text-sage-700">Patient guide · Kathmandu, Nepal</p><h1 className="mt-5 text-4xl font-bold leading-tight text-stone-950 md:text-6xl">{pillar.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-stone-600">{pillar.meta}</p><a href="tel:+9779861800547" className="mt-8 inline-block rounded-lg bg-sage-700 px-6 py-3 font-semibold text-white">Book a consultation</a></div></header>
    <article className="mx-auto grid max-w-7xl gap-10 px-6 py-14 lg:grid-cols-[260px_1fr] lg:px-8"><aside className="lg:sticky lg:top-24 lg:self-start"><nav className="rounded-lg border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Table of contents</h2>{[["introduction", "Introduction"], ...sections.map(([h]) => [h.toLowerCase().replace(/[^a-z]+/g, "-"), h]), ["when-to-see", "When to see a psychiatrist"], ["emergency", "Emergency care"], ["faqs", "FAQs"], ["myths", "Common myths"], ["online", "Online consultation"]].map(([id, label]) => <a key={id} href={`#${id}`} className="mt-2 block text-sm text-sage-700">{label}</a>)}</nav></aside><div className="space-y-6">
      <section id="introduction" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">A practical guide for patients and families</h2><p className="mt-4 leading-8">If you are searching for <strong>{pillar.keyword}</strong>, you may be trying to make sense of symptoms that have become hard to carry alone. This guide explains what an assessment involves, what evidence-based care can look like and when urgent help is needed. It is written for people in Nepal, Nepalis abroad and English-speaking visitors. It does not replace an individual diagnosis.</p><p className="mt-4 leading-8">Good psychiatric care starts with curiosity, not assumptions. Two people with the same diagnosis may need different treatment because their symptoms, physical health, family responsibilities, previous treatment and goals differ.</p></section>
      {sections.map(([heading, body]) => <section key={heading} id={heading.toLowerCase().replace(/[^a-z]+/g, "-")} className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">{heading}</h2><p className="mt-4 leading-8">{body}</p></section>)}
      <section id="how-treatment-works" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">How treatment works</h2><p className="mt-4 leading-8">Treatment is a process of testing a sensible plan against your real life. At first, the focus may be safety, sleep, distress or restoring a daily routine. As symptoms settle, care can shift towards therapy skills, relationships, work or study, physical health and the things that give life meaning. Appointments are not examinations that a patient can fail. They are a chance to review what has changed and decide, together, what should happen next.</p><p className="mt-4 leading-8">A useful plan has clear goals. Rather than only saying “feel better”, it might aim for sleeping through most nights, going back to class, taking public transport, spending less time in rituals, returning to work, or having fewer crisis days. Progress is rarely perfectly straight. A difficult week does not erase the gains made before it; it is information about stress, sleep, support or treatment that needs attention.</p><p className="mt-4 leading-8">Care should also be culturally and practically realistic. Family responsibilities, travel, language, faith, finances and privacy matter. A plan that cannot be followed is not a good plan, even if it looks ideal on paper. Discuss barriers openly so that treatment can be adapted safely.</p></section>
      <section id="first-consultation" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">What happens in the first consultation?</h2><p className="mt-4 leading-8">The first consultation begins with your own account of what has been difficult and what you hope will improve. The psychiatrist may ask about symptoms, sleep, appetite, work or study, relationships, past treatment, medical history, current medicines, alcohol or drugs, and family history. Some questions are personal because they help make care safer, but you can say when you need a question explained or a moment to think.</p><p className="mt-4 leading-8">A safety assessment is routine, not a judgement. It may include asking about thoughts of self-harm, suicide, harm to others, severe neglect or experiences that make it hard to stay safe. If a family member attends, the patient’s consent and privacy remain important. At the end, you should understand the working diagnosis or areas still being clarified, the options discussed, warning signs and how follow-up will work.</p><p className="mt-4 leading-8">It is helpful to write down questions in advance. Mention all medicines and supplements, pregnancy or breastfeeding plans where relevant, recent physical illness and any previous treatment that did or did not help. A diagnosis may be clear at one visit, or it may need time and follow-up. Thoughtful uncertainty is safer than a rushed label.</p></section>
      <section id="when-to-see" className="rounded-lg border border-sage-200 bg-sage-50 p-7"><h2 className="text-3xl font-bold">When should I see a psychiatrist?</h2><p className="mt-4 leading-8">Please arrange an assessment if symptoms last for weeks, are getting worse, interfere with sleep, self-care, work, study or relationships, or are accompanied by alcohol/drug use, self-harm thoughts, unusual experiences or major behaviour change. Early care is often simpler than waiting for a crisis.</p></section>
      <section id="emergency" className="rounded-lg border border-red-200 bg-red-50 p-7"><h2 className="text-3xl font-bold">When should I seek emergency care?</h2><p className="mt-4 leading-8">Seek immediate in-person help at the nearest emergency department if you or someone else may harm themselves or another person, cannot stay safe, is severely confused, is not caring for basic needs, has taken an overdose, or has urgent physical symptoms. Do not wait for an online appointment. Ask a trusted person to stay with you where possible.</p></section>
      <section id="myths" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">Common myths</h2><p className="mt-4 leading-8"><strong>“I should handle this alone.”</strong> Seeking assessment is responsible health care. <strong>“Medicine is always the answer.”</strong> Treatment may involve therapy, family work, lifestyle and medication only when appropriate. <strong>“Recovery means never having symptoms.”</strong> Recovery also means skills, support and a plan for difficult periods.</p></section>
      <section id="online" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">Online consultation</h2><p className="mt-4 leading-8">Online psychiatric consultation can make follow-up, psychoeducation, medication review and selected initial assessments more accessible across Nepal and for Nepalis abroad. Choose a private place, keep your medicine list nearby and share your location at the start. The clinic will advise when in-person assessment is safer.</p></section>
      <section id="faqs" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">Frequently asked questions</h2>{faqs.map(([q,a]) => <div key={q} className="mt-6"><h3 className="text-xl font-semibold">{q}</h3><p className="mt-2 leading-8">{a}</p></div>)}</section>
      <section id="references" className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-3xl font-bold">Further reading and clinical references</h2><p className="mt-4 leading-8">This patient guide is written in original language and is informed by established clinical guidance. For more detail, see the <a className="text-sage-700 underline" href="https://www.who.int/health-topics/mental-health">World Health Organization mental-health resources</a>, <a className="text-sage-700 underline" href="https://www.nice.org.uk/guidance">NICE guidance</a>, the <a className="text-sage-700 underline" href="https://www.psychiatry.org/psychiatrists/practice/clinical-practice-guidelines">American Psychiatric Association clinical practice guidelines</a>, <a className="text-sage-700 underline" href="https://www.rcpsych.ac.uk/mental-health">Royal College of Psychiatrists patient information</a>, and the <a className="text-sage-700 underline" href="https://www.nimh.nih.gov/health">US National Institute of Mental Health</a>. Diagnostic assessment is informed by current professional standards, including DSM-5-TR where clinically appropriate.</p></section>
      <section className="rounded-lg bg-sage-950 p-7 text-white"><h2 className="text-3xl font-bold">Why choose Dr. Kushal Kharel?</h2><p className="mt-4 leading-8 text-sage-100">Dr. Kushal Kharel, MD Psychiatry, is a Consultant Psychiatrist in Kathmandu. Care is grounded in careful assessment, clear explanation, evidence-based treatment and respectful partnership with patients and families.</p><p className="mt-4 leading-8 text-sage-100">Explore: {internalLinks.map(([label, href], i) => <span key={href}><Link className="underline" href={href}>{label}</Link>{i < internalLinks.length - 1 ? " · " : ""}</span>)}</p><Link href="/contact" className="mt-6 inline-block rounded-lg bg-white px-5 py-3 font-semibold text-sage-950">Contact the clinic</Link></section>
      <section className="rounded-lg border border-stone-200 bg-white p-7"><h2 className="text-2xl font-bold">Image and social media assets</h2><p className="mt-3 leading-8"><strong>Featured-image prompt:</strong> {pillar.imagePrompt}</p><p className="mt-3 leading-8"><strong>Alt text:</strong> {pillar.alt}</p><p className="mt-3 leading-8"><strong>Social snippet:</strong> Clear, compassionate information about {pillar.condition}, treatment and when to seek support in Nepal.</p><p className="mt-3 leading-8"><strong>Tweet/X:</strong> Understanding {pillar.condition} starts with an accurate assessment. Learn symptoms, evidence-based treatment and when to seek urgent care from Dr. Kushal Kharel.</p><p className="mt-3 leading-8"><strong>Facebook/LinkedIn:</strong> A practical, medically reviewed guide for patients and families in Nepal: symptoms, diagnosis, treatment choices, family support and relapse prevention for {pillar.condition}.</p></section>
      <footer className="rounded-lg border border-amber-200 bg-amber-50 p-6 text-amber-950"><p><strong>Last reviewed:</strong> July 29, 2026<br/><strong>Dr. Kushal Kharel</strong><br/>MD Psychiatry</p><p className="mt-4"><strong>Medical disclaimer:</strong> This article provides general education and is not a diagnosis, medical advice or a substitute for personal psychiatric care. For urgent safety concerns, seek immediate in-person emergency help.</p></footer>
    </div></article></main>;
}
