// GENERATED by scripts/generate-page-dates.mjs from git history (base: main). Do not edit by hand.
// Regenerate locally after adding or substantively editing a page, then commit.
// (CI checkouts are shallow, so this cannot be computed at build time.)
// Manual corrections go in scripts/page-date-overrides.json.
export const pageDates: Record<string, { published: string; modified: string }> = {
  "/": {
    "published": "2026-07-05",
    "modified": "2026-09-26"
  },
  "/about/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/addiction-treatment-kathmandu/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/adhd-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/adhd/": {
    "published": "2026-08-26",
    "modified": "2026-09-16"
  },
  "/anxiety/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/anxiety/np/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/appointment/": {
    "published": "2026-08-03",
    "modified": "2026-09-16"
  },
  "/best-psychiatrist-nepal/": {
    "published": "2026-07-20",
    "modified": "2026-09-26"
  },
  "/bipolar-disorder-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/bipolar-disorder/": {
    "published": "2026-08-26",
    "modified": "2026-09-16"
  },
  "/blog/": {
    "published": "2026-07-29",
    "modified": "2026-09-23"
  },
  "/blog/adult-adhd-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/adult-autism-late-diagnosis-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/alcohol-addiction-treatment-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-09-23"
  },
  "/blog/alcohol-drug-rehab-referral-collaboration-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/andropause-male-midlife-mental-health-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/anger-management-irritability-treatment-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/antenatal-pregnancy-anxiety-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/anxiety-vs-depression-difference-nepal/": {
    "published": "2026-08-31",
    "modified": "2026-08-31"
  },
  "/blog/bipolar-disorder-vs-depression/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/borderline-personality-disorder-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/cannabis-substance-induced-psychosis-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/career-vs-family-expectations-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/caregiver-burnout-mental-illness-dementia-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/childhood-trauma-healing-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/chronic-illness-depression-overlooked-connection-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/chronic-pain-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/dashain-tihar-festival-loneliness-depression/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/depersonalization-derealization-treatment-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/depression-vs-normal-sadness/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/divorce-separation-mental-health-impact-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/do-i-have-hiv-anxiety-testing/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/domestic-violence-mental-health-impact-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/early-signs-of-dementia-vs-normal-aging-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/earthquake-disaster-trauma-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/eating-disorders-warning-signs-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/elderly-loneliness-late-life-depression-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/erectile-dysfunction-treatment-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/exam-stress-see-board-exams-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/festival-alcohol-use-dashain-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/first-job-career-transition-anxiety-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/first-psychiatric-appointment-what-to-expect-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-31"
  },
  "/blog/free-low-cost-mental-health-services-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/gambling-addiction-treatment-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/generalized-anxiety-disorder-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/grief-bereavement-counseling-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/gutkha-tobacco-addiction-treatment-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/blog/health-anxiety-treatment-nepal/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/help-family-member-with-depression-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/how-to-choose-best-psychiatrist-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/infertility-mental-health-emotional-toll-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/insomnia-cbt-treatment-without-medication-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/internet-gaming-addiction-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/joint-family-in-law-conflict-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/ketamine-therapy-depression-anxiety-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/blog/lgbtq-mental-health-support-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/marriage-pressure-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/memory-problems-dementia-assessment-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/menopause-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/mental-health-medical-students-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/mental-health-nepali-migrant-workers/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/mental-health-nepali-students-abroad/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/mental-health-screening-tools-explained/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/mobile-overuse-technology-addiction-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/blog/monsoon-season-mental-health-nepal/": {
    "published": "2026-08-14",
    "modified": "2026-08-14"
  },
  "/blog/muscle-dysmorphia-body-image-men-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/narcissistic-personality-disorder-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/nightmares-sleep-paralysis-when-to-worry-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/ocd-common-misconceptions/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/online-psychiatric-consultation-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/opioid-heroin-brown-sugar-addiction-treatment-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/oppositional-defiant-disorder-parenting-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/overthinking-treatment-nepal/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/panic-attack-treatment-kathmandu/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/panic-attack-vs-heart-attack/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/panic-disorder-vs-generalized-anxiety-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/perfectionism-ocpd-high-standards-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/personality-testing-psychometric-assessment-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/postpartum-anxiety-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/postpartum-depression-in-fathers-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/postpartum-depression-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/postpartum-psychosis-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/premature-ejaculation-treatment-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/premenstrual-dysphoric-disorder-pmdd-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/psychiatric-doctor-kathmandu/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/psychiatric-hospitalization-inpatient-referral-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/psychiatric-medications-myths-facts/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/ptsd-treatment-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/relationship-counselling-nepal/": {
    "published": "2026-08-03",
    "modified": "2026-08-03"
  },
  "/blog/relaxation-breathing-exercises-anxiety-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/schizophrenia-early-warning-signs/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/screen-time-technology-children-parents-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/second-opinion-psychiatry-when-to-switch-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/self-harm-in-teenagers-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/sending-psychiatric-medications-abroad-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/blog/separation-anxiety-school-refusal-children-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/signs-you-should-see-a-psychiatrist/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/sleep-apnea-mental-health-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-08-07"
  },
  "/blog/sleep-problems-and-mental-health/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/smoking-cessation-quit-smoking-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/social-anxiety-treatment-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/social-media-body-image-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/somatic-symptom-disorder-treatment-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/specific-learning-disorder-dyslexia-children-nepal/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/blog/specific-phobias-treatment-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/spirituality-religion-mental-health-treatment-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/stress-management-professionals-nepal/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/blog/stress-management-therapy-counseling-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/blog/suicide-warning-signs-how-to-help-nepal/": {
    "published": "2026-08-05",
    "modified": "2026-08-06"
  },
  "/blog/whatsapp-support-between-sessions-nepal/": {
    "published": "2026-08-31",
    "modified": "2026-08-31"
  },
  "/blog/workaholism-overwork-burnout-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/cbt-therapist-kathmandu/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/child-adolescent-psychiatry/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/cities/bhaktapur/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/biratnagar/": {
    "published": "2026-07-06",
    "modified": "2026-09-16"
  },
  "/cities/butwal/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/chitwan/": {
    "published": "2026-07-06",
    "modified": "2026-08-12"
  },
  "/cities/dhangadhi/": {
    "published": "2026-07-06",
    "modified": "2026-09-16"
  },
  "/cities/dharan/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/hetauda/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/janakpur/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/kathmandu/": {
    "published": "2026-07-06",
    "modified": "2026-07-08"
  },
  "/cities/lalitpur/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/cities/nepalgunj/": {
    "published": "2026-07-06",
    "modified": "2026-09-16"
  },
  "/cities/pokhara/": {
    "published": "2026-07-06",
    "modified": "2026-08-12"
  },
  "/community-mental-health-programs/": {
    "published": "2026-07-29",
    "modified": "2026-09-26"
  },
  "/conditions/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/acute-agitation-behavioral-emergency/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/acute-stress-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/adhd/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/agoraphobia/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/alcohol-use-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/anorexia-nervosa/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/antisocial-personality-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/arfid/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/autism-spectrum-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/avoidant-personality-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/binge-eating-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/bipolar-i-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/bipolar-ii-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/body-dysmorphic-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/borderline-personality-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/brief-psychotic-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/bulimia-nervosa/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/cannabis-use-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/circadian-rhythm-sleep-wake-disorders/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/complex-ptsd/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/conduct-disorder/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/conversion-disorder/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/cyclothymic-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/delirium/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/delusional-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/depersonalization-derealization-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/conditions/erectile-dysfunction/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/conditions/excoriation-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/factitious-disorder/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/gambling-disorder/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/gaming-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/generalized-anxiety-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/hoarding-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/illness-anxiety-disorder/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/insomnia/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/intellectual-disability/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/intermittent-explosive-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/conditions/internet-addiction/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/major-depressive-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/major-neurocognitive-disorder-dementia/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/migraine-and-headache-disorders/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/conditions/mild-cognitive-impairment/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/narcissistic-personality-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/neuroleptic-malignant-syndrome/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/nicotine-dependence/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/obsessive-compulsive-personality-disorder/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/ocd/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/opioid-use-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/oppositional-defiant-disorder/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/panic-attacks/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/panic-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/parasomnias/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/persistent-depressive-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/postpartum-depression/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/postpartum-psychosis/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/premature-ejaculation/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/conditions/premenstrual-dysphoric-disorder/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/conditions/ptsd/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/schizoaffective-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/schizophrenia/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/seasonal-affective-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/separation-anxiety/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/serotonin-syndrome/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/social-anxiety-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/somatic-symptom-disorder/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/conditions/specific-learning-disorder/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/specific-phobias/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/suicide-prevention/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/conditions/trichotillomania/": {
    "published": "2026-07-07",
    "modified": "2026-09-26"
  },
  "/contact/": {
    "published": "2026-07-29",
    "modified": "2026-09-26"
  },
  "/corporate-mental-health-partner-nepal/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/counselling-in-nepal/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/couple-relationship-counseling/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/depression-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/depression/": {
    "published": "2026-08-26",
    "modified": "2026-09-16"
  },
  "/english-speaking-psychiatrist/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/erp-therapy-ocd/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/expatriates-in-nepal/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/female-counselor-kathmandu/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/help-relative-abroad-see-psychiatrist/": {
    "published": "2026-08-28",
    "modified": "2026-09-26"
  },
  "/home-visit-psychiatrist-nepal/": {
    "published": "2026-08-02",
    "modified": "2026-09-26"
  },
  "/how-to-control-your-mind-nepal/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/iq-psychological-testing/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/knowledge/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/knowledge/aalash-ho-ki-manasik-samasya-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/adhd/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/adjustment-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/knowledge/after-suicide-attempt-recovery-follow-up-care-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/aithan-sleep-paralysis-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/alcohol-addiction-treatment-nepal/": {
    "published": "2026-09-23",
    "modified": "2026-09-23"
  },
  "/knowledge/alcohol-dependence-syndrome/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/alcohol-effects-body-brain-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/alcohol-substance-use-suicide-risk-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/anxiety-depression-treatment-options-nepal/": {
    "published": "2026-09-23",
    "modified": "2026-09-23"
  },
  "/knowledge/anxiety-treatment-nepal/": {
    "published": "2026-07-20",
    "modified": "2026-09-23"
  },
  "/knowledge/autism-spectrum-disorder/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/best-psychiatrist-anxiety-depression-nepal/": {
    "published": "2026-09-23",
    "modified": "2026-09-23"
  },
  "/knowledge/best-therapy-for-anxiety/": {
    "published": "2026-09-23",
    "modified": "2026-09-23"
  },
  "/knowledge/bipolar-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/knowledge/boost-mental-health/": {
    "published": "2026-07-18",
    "modified": "2026-07-18"
  },
  "/knowledge/building-resilience/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/burnout-at-work/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/child-counselling-nepal/": {
    "published": "2026-08-24",
    "modified": "2026-08-24"
  },
  "/knowledge/coping-with-anxiety/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/counselling-services-nepal/": {
    "published": "2026-09-01",
    "modified": "2026-09-01"
  },
  "/knowledge/delirium/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/dementia/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/depression-treatment-nepal/": {
    "published": "2026-07-20",
    "modified": "2026-08-24"
  },
  "/knowledge/eating-disorder/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/elimination-disorder/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/gender-dysphoria/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/grief-and-loss/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/knowledge/help-relative-abroad-psychiatrist-nepal/": {
    "published": "2026-08-27",
    "modified": "2026-08-27"
  },
  "/knowledge/helping-your-child-everyday-mental-wellbeing-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/home-visit-psychiatric-assessment-nepal/": {
    "published": "2026-08-24",
    "modified": "2026-08-24"
  },
  "/knowledge/insomnia/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/intellectual-development-disorder/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/internet-ma-lakshan-search-garne-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/managing-depression/": {
    "published": "2026-09-23",
    "modified": "2026-09-23"
  },
  "/knowledge/mania/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/means-restriction-lethal-means-safety-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/media-werther-effect-samuhik-jimmewari/": {
    "published": "2026-07-14",
    "modified": "2026-07-14"
  },
  "/knowledge/mental-health-insurance-coverage-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/mental-health-myths-and-facts-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/mental-health-stigma/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/mindfulness-for-beginners/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/morning-drinking-alcohol-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/motor-disorder/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/non-restorative-sleep-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/nutrition-diet-mental-health-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/obsessive-compulsive-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/knowledge/overthinking-kasari-niko-parne-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/panic-attack-nepali-guide/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/panic-attacks-what-to-do/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/pesticide-self-poisoning-prevention-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/psychiatric-medication-right-or-wrong-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/psychological-first-aid-flood-landslide-nepal/": {
    "published": "2026-08-26",
    "modified": "2026-08-26"
  },
  "/knowledge/ptsd/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/restless-legs-syndrome/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/schizophrenia/": {
    "published": "2026-07-06",
    "modified": "2026-07-06"
  },
  "/knowledge/self-care-caregivers/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/sexual-health-performance-anxiety-intimacy-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/sleep-and-mental-health/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/sleep-problems-which-doctor-kathmandu/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/smiling-depression-nepal/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/social-media-mental-health/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/substance-use-disorder/": {
    "published": "2026-08-05",
    "modified": "2026-08-05"
  },
  "/knowledge/suicide-crisis-helplines-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/suicide-in-nepal-facts-myths-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/suicide-loss-postvention-grief-support-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/suicide-risk-nepali-migrant-workers-abroad/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/suicide-safety-plan-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/teen-mental-health-parents/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/therapy-types-explained/": {
    "published": "2026-08-02",
    "modified": "2026-08-02"
  },
  "/knowledge/therapy-vs-medication-which-is-right-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/knowledge/when-do-you-need-counselling/": {
    "published": "2026-09-02",
    "modified": "2026-09-02"
  },
  "/knowledge/yati-sano-kurama/": {
    "published": "2026-07-14",
    "modified": "2026-07-14"
  },
  "/knowledge/youth-suicide-prevention-gatekeeper-guide-parents-teachers-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-08-06"
  },
  "/medical-disclaimer/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/medical-fitness-certificate/": {
    "published": "2026-08-05",
    "modified": "2026-09-26"
  },
  "/medication-review-second-opinion-nepal/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/medications/": {
    "published": "2026-08-12",
    "modified": "2026-09-16"
  },
  "/medications/antipsychotic-medications-explained/": {
    "published": "2026-08-12",
    "modified": "2026-08-12"
  },
  "/medications/benzodiazepines-explained/": {
    "published": "2026-08-12",
    "modified": "2026-08-12"
  },
  "/medications/mood-stabilizers-lithium-explained/": {
    "published": "2026-08-12",
    "modified": "2026-08-12"
  },
  "/medications/ssris-explained/": {
    "published": "2026-08-12",
    "modified": "2026-08-12"
  },
  "/mental-health-screening/": {
    "published": "2026-07-29",
    "modified": "2026-07-29"
  },
  "/nepalese-abroad/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/australia/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/bahrain/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/nepalese-abroad/bangladesh/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/belgium/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/brunei/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/canada/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/china/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/croatia/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/cyprus/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/denmark/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/dubai/": {
    "published": "2026-07-06",
    "modified": "2026-08-19"
  },
  "/nepalese-abroad/east-asia/": {
    "published": "2026-09-26",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/europe/": {
    "published": "2026-09-26",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/fiji/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/finland/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/france/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/germany/": {
    "published": "2026-08-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/gulf/": {
    "published": "2026-09-26",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/hong-kong/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/india/": {
    "published": "2026-07-06",
    "modified": "2026-08-05"
  },
  "/nepalese-abroad/ireland/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/israel/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/italy/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/japan/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/korea/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/kuwait/": {
    "published": "2026-08-14",
    "modified": "2026-08-14"
  },
  "/nepalese-abroad/malaysia/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/myanmar/": {
    "published": "2026-08-19",
    "modified": "2026-08-19"
  },
  "/nepalese-abroad/netherlands/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/new-zealand/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/norway/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/oman/": {
    "published": "2026-08-18",
    "modified": "2026-08-18"
  },
  "/nepalese-abroad/poland/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/portugal/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/qatar/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/romania/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/saudi-arabia/": {
    "published": "2026-08-12",
    "modified": "2026-08-12"
  },
  "/nepalese-abroad/singapore/": {
    "published": "2026-08-18",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/southeast-asia/": {
    "published": "2026-09-26",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/spain/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/sri-lanka/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/sweden/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/thailand/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/uk/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/nepalese-abroad/usa/": {
    "published": "2026-07-06",
    "modified": "2026-08-19"
  },
  "/ocd/": {
    "published": "2026-08-26",
    "modified": "2026-09-16"
  },
  "/online-psychiatrist-nepal/": {
    "published": "2026-07-20",
    "modified": "2026-09-26"
  },
  "/panic-attack-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/patient-testimonials/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/privacy-policy/": {
    "published": "2026-07-08",
    "modified": "2026-09-16"
  },
  "/psychiatric-care-for-family-in-nepal/": {
    "published": "2026-08-19",
    "modified": "2026-09-26"
  },
  "/psychiatric-hospital-vs-clinic-kathmandu/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/psychiatric-medication-side-effects/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/psychiatrist-fee-nepal/": {
    "published": "2026-08-07",
    "modified": "2026-09-26"
  },
  "/psychiatrist-for-nepalis-abroad/": {
    "published": "2026-07-29",
    "modified": "2026-09-26"
  },
  "/psychiatry-clinic-kathmandu/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/psychology-internship-nepal/": {
    "published": "2026-08-06",
    "modified": "2026-09-16"
  },
  "/psychosis-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/relationship-counselling-kathmandu/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/resources/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/adhd-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/adhd-stimulant-medications-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/alcohol-use-disorder-family-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/alcohol-use-disorder-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/antidepressants-ssri-snri-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/antipsychotics-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/anxiety-coping-cards/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/benzodiazepines-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/bipolar-i-disorder-family-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/bipolar-i-disorder-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/breathing-exercise-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/caregiver-support-resource/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/generalized-anxiety-disorder-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/insomnia-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/major-depressive-disorder-family-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/major-depressive-disorder-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/mood-stabilizers-guide/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/resources/ocd-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/panic-attacks-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/panic-disorder-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/schizophrenia-family-guide/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/resources/schizophrenia-leaflet/": {
    "published": "2026-07-09",
    "modified": "2026-09-26"
  },
  "/returning-to-nepal-after-abroad/": {
    "published": "2026-08-14",
    "modified": "2026-09-26"
  },
  "/schizophrenia-treatment-kathmandu/": {
    "published": "2026-08-21",
    "modified": "2026-09-26"
  },
  "/schizophrenia/": {
    "published": "2026-08-26",
    "modified": "2026-09-16"
  },
  "/screening/": {
    "published": "2026-07-06",
    "modified": "2026-09-26"
  },
  "/screening/adult-adhd/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/alcohol-use/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/anxiety/": {
    "published": "2026-07-06",
    "modified": "2026-07-09"
  },
  "/screening/bipolar/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/depression/": {
    "published": "2026-07-06",
    "modified": "2026-07-09"
  },
  "/screening/eating-disorder/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/insomnia/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/ocd/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/panic-disorder/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/postpartum-depression/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/ptsd/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/screening/sleepiness/": {
    "published": "2026-07-06",
    "modified": "2026-07-09"
  },
  "/screening/social-anxiety/": {
    "published": "2026-07-09",
    "modified": "2026-07-09"
  },
  "/sleep-problems-treatment-nepal/": {
    "published": "2026-09-24",
    "modified": "2026-09-26"
  },
  "/stress-anger-management-kathmandu/": {
    "published": "2026-08-12",
    "modified": "2026-09-26"
  },
  "/tourists-in-nepal/": {
    "published": "2026-07-08",
    "modified": "2026-09-26"
  }
};

export function getPageDates(path: string) {
  return pageDates[path.endsWith("/") ? path : `${path}/`];
}
