#!/usr/bin/env node
/**
 * SEO audit for the static export in `out/`.
 *
 * Crawls every built page and reports, per page: title length, description
 * length, H1 count, canonical, <html lang> vs the language the body is really
 * written in, hreflang, og:locale, JSON-LD types (flagging AggregateRating),
 * word count, internal inlinks (all + contextual), and broken internal links.
 * Then prints a summary table of site-wide metrics.
 *
 * No dependencies — the HTML is machine-generated by Next, so a small tag
 * tokenizer is enough and keeps this runnable in CI right after `next build`.
 *
 * Usage:
 *   node scripts/seo-audit.mjs                       # summary table
 *   node scripts/seo-audit.mjs --json audit.json     # also save full per-page data
 *   node scripts/seo-audit.mjs --compare before.json # before/after diff table
 *   node scripts/seo-audit.mjs --list titleTooLong   # URLs behind one metric
 *   node scripts/seo-audit.mjs --page /about/        # full detail for one page
 *   node scripts/seo-audit.mjs --strict              # exit 1 on hard failures (CI)
 *
 * Options: --out <dir> (default "out"), --site <origin> (default the live site).
 */
import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------- CLI args
const args = process.argv.slice(2);
function flag(name) {
  return args.includes(`--${name}`);
}
function opt(name, fallback) {
  const i = args.indexOf(`--${name}`);
  return i !== -1 && args[i + 1] && !args[i + 1].startsWith("--") ? args[i + 1] : fallback;
}

const OUT_DIR = path.resolve(opt("out", "out"));
const SITE = opt("site", "https://drkushalkharel.com.np").replace(/\/$/, "");
const THIN_WORDS = 450;
const TITLE_MAX = 60;
const DESC_MAX = 160;
const DESC_MIN = 120;
// Built pages carry English template text (nav, FAQ, CTA), so their Devanagari
// share runs lower than the article text alone. Above NE the page is Nepali;
// below EN it is English; in between it is a bilingual page and either <html lang>
// is accepted (the site declares those "en" and marks Nepali paragraphs inline).
const DEVANAGARI_NE_ABOVE = 0.5;
const DEVANAGARI_EN_BELOW = 0.3;

if (!fs.existsSync(OUT_DIR)) {
  console.error(`No build output at ${OUT_DIR}. Run \`npm run build\` first.`);
  process.exit(2);
}

// ------------------------------------------------------------- HTML helpers
const ENTITIES = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " " };
function decode(str = "") {
  return str.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e) => {
    if (e[0] === "#") {
      const code = e[1].toLowerCase() === "x" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    return ENTITIES[e.toLowerCase()] ?? m;
  });
}

const ATTR_RE = /([a-zA-Z_:][-a-zA-Z0-9_:.]*)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+)))?/g;
function parseAttrs(raw) {
  const attrs = {};
  for (const m of raw.matchAll(ATTR_RE)) {
    attrs[m[1].toLowerCase()] = decode(m[2] ?? m[3] ?? m[4] ?? "");
  }
  return attrs;
}

// Comment | tag (attribute values may legally contain ">")
const TAG_RE = /<!--[\s\S]*?-->|<(\/?)([a-zA-Z][a-zA-Z0-9-]*)((?:"[^"]*"|'[^']*'|[^>"'])*)>/g;
const SKIP_CONTENT = new Set(["script", "style", "noscript", "svg", "template"]);
const CHROME = new Set(["nav", "header", "footer", "aside"]);
const VOID = new Set(["meta", "link", "img", "br", "hr", "input", "source", "area", "base", "col", "embed", "track", "wbr"]);

function collectJsonLd(html) {
  const blocks = [];
  const re = /<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  for (const m of html.matchAll(re)) {
    try {
      blocks.push({ ok: true, data: JSON.parse(m[1]) });
    } catch (error) {
      blocks.push({ ok: false, error: String(error.message ?? error), raw: m[1].slice(0, 200) });
    }
  }
  return blocks;
}

function jsonLdNodes(data, into = []) {
  if (Array.isArray(data)) {
    data.forEach((item) => jsonLdNodes(item, into));
  } else if (data && typeof data === "object") {
    into.push(data);
    for (const value of Object.values(data)) jsonLdNodes(value, into);
  }
  return into;
}

function typesOf(node) {
  const t = node["@type"];
  return Array.isArray(t) ? t : t ? [t] : [];
}

function parsePage(html) {
  const headEnd = html.search(/<\/head>/i);
  const head = headEnd === -1 ? "" : html.slice(0, headEnd);
  const htmlTag = html.match(/<html\b([^>]*)>/i);
  const lang = htmlTag ? parseAttrs(htmlTag[1]).lang ?? null : null;

  const titleMatch = head.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? decode(titleMatch[1]).trim() : "";

  const meta = {};
  const hreflang = [];
  let canonical = null;
  for (const m of head.matchAll(TAG_RE)) {
    if (!m[2]) continue;
    const tag = m[2].toLowerCase();
    if (tag === "meta") {
      const a = parseAttrs(m[3]);
      const key = a.name ?? a.property;
      if (key && a.content !== undefined) meta[key.toLowerCase()] = a.content;
    } else if (tag === "link") {
      const a = parseAttrs(m[3]);
      if (a.rel === "canonical") canonical = a.href ?? null;
      if (a.rel === "alternate" && a.hreflang) hreflang.push({ lang: a.hreflang, href: a.href });
    }
  }

  const jsonLd = collectJsonLd(html);

  // Walk the body once, tracking landmark depth so we can tell contextual
  // links/text from navigation chrome.
  const bodyStart = html.search(/<body\b/i);
  const body = bodyStart === -1 ? "" : html.slice(bodyStart);
  const links = [];
  const imgs = [];
  let h1Count = 0;
  let h1Text = "";
  let inH1 = false;
  let skipTag = null;
  let skipDepth = 0;
  let chromeDepth = 0;
  let allText = "";
  let contentText = "";
  let last = 0;

  const pushText = (chunk) => {
    if (skipTag) return;
    const t = decode(chunk);
    allText += ` ${t}`;
    if (chromeDepth === 0) contentText += ` ${t}`;
    if (inH1) h1Text += ` ${t}`;
  };

  for (const m of body.matchAll(TAG_RE)) {
    pushText(body.slice(last, m.index));
    last = m.index + m[0].length;
    if (!m[2]) continue; // comment
    const closing = m[1] === "/";
    const tag = m[2].toLowerCase();

    if (skipTag) {
      if (tag === skipTag) {
        if (closing) {
          skipDepth -= 1;
          if (skipDepth === 0) skipTag = null;
        } else if (!m[0].endsWith("/>")) {
          skipDepth += 1;
        }
      }
      continue;
    }
    if (!closing && SKIP_CONTENT.has(tag) && !m[0].endsWith("/>")) {
      skipTag = tag;
      skipDepth = 1;
      continue;
    }

    if (CHROME.has(tag)) chromeDepth = Math.max(0, chromeDepth + (closing ? -1 : 1));
    if (tag === "h1") {
      if (closing) inH1 = false;
      else {
        h1Count += 1;
        inH1 = true;
      }
    }
    if (closing || VOID.has(tag) === false) {
      // no-op: only openers matter for attributes below
    }
    if (!closing && tag === "a") {
      const a = parseAttrs(m[3]);
      if (a.href) links.push({ href: a.href, contextual: chromeDepth === 0 });
    }
    if (!closing && tag === "img") {
      const a = parseAttrs(m[3]);
      imgs.push({ src: a.src ?? "", alt: a.alt });
    }
  }
  pushText(body.slice(last));

  const words = allText.split(/\s+/).filter(Boolean).length;
  const dev = (contentText.match(/[ऀ-ॿ]/g) ?? []).length;
  const latin = (contentText.match(/[A-Za-z]/g) ?? []).length;
  const devanagariRatio = dev + latin === 0 ? 0 : dev / (dev + latin);

  return {
    lang,
    title,
    description: meta.description ?? "",
    robots: meta.robots ?? "",
    canonical,
    hreflang,
    ogLocale: meta["og:locale"] ?? null,
    ogTitle: meta["og:title"] ?? null,
    h1Count,
    h1Text: h1Text.replace(/\s+/g, " ").trim(),
    jsonLd,
    links,
    imgs,
    words,
    devanagariRatio,
  };
}

// ---------------------------------------------------------- crawl out/
function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const allFiles = walk(OUT_DIR);
const fileSet = new Set(allFiles.map((f) => "/" + path.relative(OUT_DIR, f).split(path.sep).join("/")));

function toUrlPath(file) {
  const rel = "/" + path.relative(OUT_DIR, file).split(path.sep).join("/");
  if (rel === "/index.html") return "/";
  if (rel.endsWith("/index.html")) return rel.slice(0, -"index.html".length);
  return null;
}

// Sitemap
function readSitemap() {
  const file = path.join(OUT_DIR, "sitemap.xml");
  if (!fs.existsSync(file)) return { urls: new Map() };
  const xml = fs.readFileSync(file, "utf8");
  const urls = new Map();
  for (const m of xml.matchAll(/<url>([\s\S]*?)<\/url>/g)) {
    const block = m[1];
    const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
    if (!loc) continue;
    const lastmod = block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1] ?? null;
    const alternates = [...block.matchAll(/<xhtml:link\b([^>]*)\/?>/g)].map((a) => {
      const at = parseAttrs(a[1]);
      return { lang: at.hreflang, href: at.href };
    });
    urls.set(decode(loc).replace(SITE, "") || "/", { lastmod, alternates });
  }
  return { urls };
}
const sitemap = readSitemap();

const pages = new Map();
for (const file of allFiles) {
  const urlPath = toUrlPath(file);
  if (!urlPath) continue;
  if (urlPath.startsWith("/_next/") || urlPath.startsWith("/_not-found/") || urlPath === "/404/") continue;
  const html = fs.readFileSync(file, "utf8");
  const parsed = parsePage(html);
  pages.set(urlPath, { url: urlPath, htmlBytes: Buffer.byteLength(html), ...parsed });
}

// Is a same-site href something that exists in the build?
function normalizeHref(href) {
  let h = href.trim();
  if (!h || h.startsWith("#") || /^(mailto:|tel:|sms:|javascript:|data:|whatsapp:)/i.test(h)) return null;
  if (/^https?:\/\//i.test(h)) {
    if (!h.startsWith(SITE) && !h.startsWith(SITE.replace("https://", "http://"))) return null;
    h = h.replace(/^https?:\/\/[^/]+/i, "") || "/";
  }
  if (h.startsWith("//")) return null;
  if (!h.startsWith("/")) return { relative: true, raw: href };
  h = h.split("#")[0].split("?")[0];
  return { path: h || "/" };
}

function resolveTarget(p) {
  if (pages.has(p)) return { kind: "page", path: p };
  if (!p.endsWith("/") && pages.has(p + "/")) return { kind: "page", path: p + "/", missingSlash: true };
  if (fileSet.has(p)) return { kind: "file", path: p };
  try {
    const decodedPath = decodeURI(p);
    if (pages.has(decodedPath)) return { kind: "page", path: decodedPath };
    if (fileSet.has(decodedPath)) return { kind: "file", path: decodedPath };
  } catch {
    /* ignore malformed URI */
  }
  return null;
}

const isIndexable = (page) => !/noindex/i.test(page.robots);

// ------------------------------------------------------------- link graph
const inlinksAll = new Map();
const inlinksContextual = new Map();
for (const url of pages.keys()) {
  inlinksAll.set(url, new Set());
  inlinksContextual.set(url, new Set());
}

const brokenLinks = [];
const linksToStubs = [];
const missingSlashLinks = [];
const relativeLinks = [];
const brokenImages = [];

for (const page of pages.values()) {
  const outlinks = new Set();
  const indexableSource = isIndexable(page);
  for (const link of page.links) {
    const n = normalizeHref(link.href);
    if (!n) continue;
    if (n.relative) {
      relativeLinks.push({ source: page.url, href: link.href });
      continue;
    }
    const target = resolveTarget(n.path);
    if (!target) {
      brokenLinks.push({ source: page.url, href: link.href });
      continue;
    }
    if (target.missingSlash) missingSlashLinks.push({ source: page.url, href: link.href });
    if (target.kind !== "page" || target.path === page.url) continue;
    outlinks.add(target.path);
    if (!indexableSource) continue; // links from noindex stubs don't pass value
    inlinksAll.get(target.path).add(page.url);
    if (link.contextual) inlinksContextual.get(target.path).add(page.url);
    if (!isIndexable(pages.get(target.path))) linksToStubs.push({ source: page.url, href: link.href });
  }
  page.outlinks = outlinks.size;
  for (const img of page.imgs) {
    if (img.src.startsWith("/") && !resolveTarget(img.src.split("?")[0])) {
      brokenImages.push({ source: page.url, src: img.src });
    }
  }
}

// ------------------------------------------------------------ per-page rows
const rows = [...pages.values()]
  .sort((a, b) => a.url.localeCompare(b.url))
  .map((page) => {
    const nodes = page.jsonLd.filter((b) => b.ok).flatMap((b) => jsonLdNodes(b.data));
    const types = [...new Set(nodes.flatMap(typesOf))].sort();
    const physicianNodes = nodes.filter((n) => typesOf(n).includes("Physician") && n.address);
    const expectedLang =
      page.devanagariRatio > DEVANAGARI_NE_ABOVE ? "ne" : page.devanagariRatio < DEVANAGARI_EN_BELOW ? "en" : "either";
    const actualLang = (page.lang ?? "").toLowerCase().split("-")[0];
    const canonicalExpected = SITE + page.url;
    const hreflangLangs = page.hreflang.map((h) => h.lang);
    return {
      url: page.url,
      indexable: isIndexable(page),
      inSitemap: sitemap.urls.has(page.url),
      lang: page.lang,
      expectedLang,
      langMismatch: expectedLang !== "either" && actualLang !== expectedLang,
      devanagariRatio: Number(page.devanagariRatio.toFixed(3)),
      ogLocale: page.ogLocale,
      title: page.title,
      titleLen: [...page.title].length,
      description: page.description,
      descLen: [...page.description].length,
      h1Count: page.h1Count,
      h1: page.h1Text,
      canonical: page.canonical,
      canonicalOk: page.canonical === canonicalExpected,
      hreflang: page.hreflang,
      hasXDefault: hreflangLangs.includes("x-default"),
      jsonLdTypes: types,
      jsonLdBlocks: page.jsonLd.length,
      jsonLdInvalid: page.jsonLd.filter((b) => !b.ok).length,
      hasAggregateRating: types.includes("AggregateRating"),
      hasFullPhysician: physicianNodes.length > 0,
      hasDatePublished: nodes.some((n) => n.datePublished),
      hasDateModified: nodes.some((n) => n.dateModified),
      words: page.words,
      htmlBytes: page.htmlBytes,
      inlinks: inlinksAll.get(page.url).size,
      contextualInlinks: inlinksContextual.get(page.url).size,
      outlinks: page.outlinks,
      imgs: page.imgs.length,
      imgsMissingAlt: page.imgs.filter((i) => i.alt === undefined).length,
      broken: brokenLinks.filter((b) => b.source === page.url).map((b) => b.href),
    };
  });

const byUrl = new Map(rows.map((r) => [r.url, r]));
const indexable = rows.filter((r) => r.indexable);
const sitemapRows = rows.filter((r) => r.inSitemap);

// hreflang reciprocity: A -> B requires B -> A, and every set must self-reference.
const hreflangErrors = [];
for (const r of rows.filter((r) => r.hreflang.length)) {
  const selfListed = r.hreflang.some((h) => h.href === SITE + r.url);
  if (!selfListed) hreflangErrors.push({ url: r.url, problem: "does not list itself" });
  for (const h of r.hreflang) {
    const targetPath = (h.href ?? "").replace(SITE, "");
    const target = byUrl.get(targetPath);
    if (!target) hreflangErrors.push({ url: r.url, problem: `points to missing page ${h.href}` });
    else if (!target.hreflang.some((t) => t.href === SITE + r.url)) {
      hreflangErrors.push({ url: r.url, problem: `${targetPath} does not link back` });
    }
  }
}

// Titles/descriptions shared by more than one indexable page.
function duplicates(field) {
  const groups = new Map();
  for (const r of indexable) {
    if (!r[field]) continue;
    (groups.get(r[field]) ?? groups.set(r[field], []).get(r[field])).push(r.url);
  }
  return [...groups.values()].filter((g) => g.length > 1);
}
const dupTitles = duplicates("title");
const dupDescriptions = duplicates("description");

// Sitemap lastmod: how many URLs share the single most common date?
const lastmodCounts = new Map();
for (const { lastmod } of sitemap.urls.values()) {
  const day = (lastmod ?? "none").slice(0, 10);
  lastmodCounts.set(day, (lastmodCounts.get(day) ?? 0) + 1);
}
const topLastmod = [...lastmodCounts.entries()].sort((a, b) => b[1] - a[1])[0] ?? ["none", 0];

// ------------------------------------------------------------ metrics
const metricDefs = [
  // key, label, urls (array of url strings) — count is urls.length
  ["pagesBuilt", "HTML pages built", rows.map((r) => r.url)],
  ["sitemapUrls", "URLs in sitemap.xml", sitemapRows.map((r) => r.url)],
  ["notIndexable", "Built pages with noindex", rows.filter((r) => !r.indexable).map((r) => r.url)],
  ["sitemapMissingPage", "Sitemap URLs with no built page", [...sitemap.urls.keys()].filter((u) => !byUrl.has(u))],
  ["sitemapNoindex", "Sitemap URLs that are noindex", sitemapRows.filter((r) => !r.indexable).map((r) => r.url)],
  ["langMismatch", "Indexable pages where <html lang> ≠ body language", indexable.filter((r) => r.langMismatch).map((r) => r.url)],
  ["langNe", 'Indexable pages rendered with lang="ne"', indexable.filter((r) => (r.lang ?? "").startsWith("ne")).map((r) => r.url)],
  ["ogLocaleMismatch", "Indexable pages where og:locale disagrees with lang", indexable.filter((r) => {
    const langIsNe = (r.lang ?? "").toLowerCase().startsWith("ne");
    const localeIsNe = /^ne/.test(r.ogLocale ?? "");
    return langIsNe !== localeIsNe;
  }).map((r) => r.url)],
  ["hreflangPages", "Pages with hreflang alternates", indexable.filter((r) => r.hreflang.length).map((r) => r.url)],
  ["hreflangNoXDefault", "hreflang sets missing x-default", indexable.filter((r) => r.hreflang.length && !r.hasXDefault).map((r) => r.url)],
  ["hreflangErrors", "hreflang reciprocity/self-reference errors", hreflangErrors.map((e) => `${e.url} — ${e.problem}`)],
  ["aggregateRating", "Pages with AggregateRating in JSON-LD", rows.filter((r) => r.hasAggregateRating).map((r) => r.url)],
  ["fullPhysician", "Pages carrying a full Physician block (with address)", rows.filter((r) => r.hasFullPhysician).map((r) => r.url)],
  ["jsonLdInvalid", "Pages with unparseable JSON-LD", rows.filter((r) => r.jsonLdInvalid).map((r) => r.url)],
  ["titleMissing", "Indexable pages with no <title>", indexable.filter((r) => !r.titleLen).map((r) => r.url)],
  ["titleTooLong", `Titles longer than ${TITLE_MAX} chars`, indexable.filter((r) => r.titleLen > TITLE_MAX).map((r) => r.url)],
  ["titleDoubleBrand", "Titles repeating the brand name twice", indexable.filter((r) => (r.title.match(/Dr\.? Kushal Kharel/gi) ?? []).length > 1).map((r) => r.url)],
  ["titleDuplicate", "Pages sharing a title with another page", dupTitles.flat()],
  ["descMissing", "Indexable pages with no meta description", indexable.filter((r) => !r.descLen).map((r) => r.url)],
  ["descTooLong", `Descriptions longer than ${DESC_MAX} chars`, indexable.filter((r) => r.descLen > DESC_MAX).map((r) => r.url)],
  ["descTooShort", `Descriptions shorter than ${DESC_MIN} chars`, indexable.filter((r) => r.descLen && r.descLen < DESC_MIN).map((r) => r.url)],
  ["descDuplicate", "Pages sharing a description with another page", dupDescriptions.flat()],
  ["h1NotOne", "Indexable pages without exactly one H1", indexable.filter((r) => r.h1Count !== 1).map((r) => r.url)],
  ["canonicalBad", "Indexable pages whose canonical ≠ own URL", indexable.filter((r) => !r.canonicalOk).map((r) => r.url)],
  ["thinPages", `Indexable pages under ${THIN_WORDS} words`, indexable.filter((r) => r.words < THIN_WORDS).map((r) => r.url)],
  ["orphans", "Indexable pages with 0 inlinks from indexable pages", indexable.filter((r) => r.inlinks === 0).map((r) => r.url)],
  ["contextualOrphans", "Indexable pages with 0 contextual inlinks (excl. nav/footer)", indexable.filter((r) => r.contextualInlinks === 0).map((r) => r.url)],
  ["contextualLe1", "Indexable pages with ≤1 contextual inlinks", indexable.filter((r) => r.contextualInlinks <= 1).map((r) => r.url)],
  ["contextualLt3", "Indexable pages with <3 contextual inlinks", indexable.filter((r) => r.contextualInlinks < 3).map((r) => r.url)],
  ["brokenLinks", "Broken internal links (404s)", brokenLinks.map((b) => `${b.source} → ${b.href}`)],
  ["brokenImages", "Broken internal images", brokenImages.map((b) => `${b.source} → ${b.src}`)],
  ["linksToStubs", "Internal links pointing at noindex/redirect stubs", linksToStubs.map((b) => `${b.source} → ${b.href}`)],
  ["missingSlashLinks", "Internal links missing trailing slash", missingSlashLinks.map((b) => `${b.source} → ${b.href}`)],
  ["imgMissingAlt", "Pages with <img> lacking an alt attribute", rows.filter((r) => r.imgsMissingAlt).map((r) => r.url)],
];

const metrics = Object.fromEntries(
  metricDefs.map(([key, label, urls]) => [key, { label, count: urls.length, urls }]),
);
// Scalar metrics with no URL list
const home = byUrl.get("/");
const scalars = {
  sitemapLastmodTopDayCount: { label: `Sitemap URLs sharing the most common lastmod (${topLastmod[0]})`, count: topLastmod[1] },
  sitemapLastmodDistinct: { label: "Distinct lastmod dates in sitemap", count: lastmodCounts.size },
  homeWords: { label: "Homepage word count", count: home?.words ?? 0 },
  homeKb: { label: "Homepage HTML size (KB)", count: home ? Math.round(home.htmlBytes / 1024) : 0 },
  medianWords: {
    label: "Median words per indexable page",
    count: indexable.map((r) => r.words).sort((a, b) => a - b)[Math.floor(indexable.length / 2)] ?? 0,
  },
};

// ------------------------------------------------------------ output
function printSummary() {
  console.log(`\nSEO audit of ${path.relative(process.cwd(), OUT_DIR) || "."}/  (${rows.length} pages, ${sitemap.urls.size} in sitemap)\n`);
  const width = Math.max(...Object.values(metrics).map((m) => m.label.length), ...Object.values(scalars).map((s) => s.label.length));
  for (const m of [...Object.values(metrics), ...Object.values(scalars)]) {
    console.log(`  ${m.label.padEnd(width)}  ${String(m.count).padStart(6)}`);
  }
  console.log("");
}

function printCompare(beforeFile) {
  const before = JSON.parse(fs.readFileSync(beforeFile, "utf8")).summary;
  const now = { ...Object.fromEntries(Object.entries(metrics).map(([k, v]) => [k, v.count])), ...Object.fromEntries(Object.entries(scalars).map(([k, v]) => [k, v.count])) };
  const labels = { ...Object.fromEntries(Object.entries(metrics).map(([k, v]) => [k, v.label])), ...Object.fromEntries(Object.entries(scalars).map(([k, v]) => [k, v.label])) };
  const keys = Object.keys(now);
  console.log("\n| Metric | Before | After | Δ |\n|---|---:|---:|---:|");
  for (const key of keys) {
    const b = before[key];
    const a = now[key];
    if (b === undefined) continue;
    if (b === a && !flag("all")) continue;
    const d = a - b;
    console.log(`| ${labels[key]} | ${b} | ${a} | ${d > 0 ? "+" : ""}${d} |`);
  }
  console.log("");
}

const listKey = opt("list");
const pageArg = opt("page");
const compareFile = opt("compare");
const jsonFile = opt("json");

if (jsonFile) {
  const summary = { ...Object.fromEntries(Object.entries(metrics).map(([k, v]) => [k, v.count])), ...Object.fromEntries(Object.entries(scalars).map(([k, v]) => [k, v.count])) };
  fs.writeFileSync(jsonFile, JSON.stringify({ generatedAt: new Date().toISOString(), summary, metrics, pages: rows }, null, 2));
  console.log(`Wrote ${jsonFile}`);
}

if (pageArg) {
  const row = byUrl.get(pageArg);
  console.log(row ? JSON.stringify(row, null, 2) : `No built page at ${pageArg}`);
} else if (listKey) {
  const m = metrics[listKey];
  if (!m) {
    console.error(`Unknown metric "${listKey}". Available: ${Object.keys(metrics).join(", ")}`);
    process.exit(2);
  }
  console.log(`${m.label}: ${m.count}`);
  m.urls.forEach((u) => console.log(`  ${u}`));
} else if (compareFile) {
  printCompare(compareFile);
} else {
  printSummary();
}

// -------------------------------------------------------------- --strict
if (flag("strict")) {
  // Hard failures only: things that are objectively wrong, not style targets.
  const hard = ["brokenLinks", "brokenImages", "langMismatch", "aggregateRating", "jsonLdInvalid", "h1NotOne", "canonicalBad", "sitemapMissingPage", "sitemapNoindex", "hreflangErrors"];
  const failures = hard.filter((k) => metrics[k].count > 0);
  if (failures.length) {
    console.error("\nSEO audit FAILED:");
    for (const k of failures) {
      console.error(`  ✗ ${metrics[k].label}: ${metrics[k].count}`);
      metrics[k].urls.slice(0, 15).forEach((u) => console.error(`      ${u}`));
      if (metrics[k].urls.length > 15) console.error(`      … and ${metrics[k].urls.length - 15} more`);
    }
    process.exit(1);
  }
  console.log("SEO audit passed (strict checks).");
}
